import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'

export default function Home() {

  function acessar() {
    console.log('acessou');
    
    axios.post('https://dmtt-api.herokuapp.com/api/user/login',{
      email: 'robson.dev9@gmail.com',
      password: '123456'
    }).then(res => console.log(res)).catch(e => console.log(e))
    
    
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Login</h1>

      <button onClick={acessar}>Acessar</button>

     
    </div>
  )
}
